
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.analizador.ascendente.sintactico;

/** CUP generated class containing symbol constants. */
public class CUPSim {
  /* terminals */
  public static final int r_true = 16;
  public static final int r_nulo = 2;
  public static final int r_return = 10;
  public static final int mod = 23;
  public static final int dospu = 30;
  public static final int flecha = 44;
  public static final int r_false = 17;
  public static final int llave_c = 40;
  public static final int r_function = 15;
  public static final int llave_a = 39;
  public static final int r_else = 4;
  public static final int coma = 28;
  public static final int igual = 38;
  public static final int r_switch = 5;
  public static final int cor_c = 27;
  public static final int identificador = 45;
  public static final int cor_a = 26;
  public static final int r_default = 7;
  public static final int r_continue = 9;
  public static final int igualdad = 37;
  public static final int r_in = 14;
  public static final int numero_decimal = 47;
  public static final int menos = 19;
  public static final int r_if = 3;
  public static final int menor = 32;
  public static final int EOF = 0;
  public static final int mayor_igual = 35;
  public static final int mas = 18;
  public static final int uminus = 49;
  public static final int error = 1;
  public static final int mayor = 33;
  public static final int r_for = 12;
  public static final int or = 41;
  public static final int pot = 22;
  public static final int por = 20;
  public static final int menor_igual = 34;
  public static final int r_case = 6;
  public static final int numero_entero = 46;
  public static final int not = 43;
  public static final int and = 42;
  public static final int r_break = 8;
  public static final int diferente_que = 36;
  public static final int div = 21;
  public static final int par_c = 25;
  public static final int par_a = 24;
  public static final int puco = 29;
  public static final int interrogacion = 31;
  public static final int r_while = 11;
  public static final int cadena = 48;
  public static final int r_do = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "r_nulo",
  "r_if",
  "r_else",
  "r_switch",
  "r_case",
  "r_default",
  "r_break",
  "r_continue",
  "r_return",
  "r_while",
  "r_for",
  "r_do",
  "r_in",
  "r_function",
  "r_true",
  "r_false",
  "mas",
  "menos",
  "por",
  "div",
  "pot",
  "mod",
  "par_a",
  "par_c",
  "cor_a",
  "cor_c",
  "coma",
  "puco",
  "dospu",
  "interrogacion",
  "menor",
  "mayor",
  "menor_igual",
  "mayor_igual",
  "diferente_que",
  "igualdad",
  "igual",
  "llave_a",
  "llave_c",
  "or",
  "and",
  "not",
  "flecha",
  "identificador",
  "numero_entero",
  "numero_decimal",
  "cadena",
  "uminus"
  };
}

