/* The following code was generated by JFlex 1.7.0 */

/************************* 1RA AREA: CÓDIGO DE USUARIO *************************/

/* PAQUETES E IMPORTACIONES */
package com.analizador.ascendente.lexico;

import com.estaticas.ErrorHandler;
import com.analizador.ascendente.sintactico.CUPSim;
import java_cup.runtime.*;

/********************** 2DA AREA: OPCIONES Y DECLARACIONES *********************/


public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING_CAPTURE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int[] ZZ_LEXSTATE = {
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\64\1\6\1\65\1\64\1\5\22\0\1\64\1\55\1\62"+
    "\1\7\1\0\1\41\1\61\1\0\1\42\1\43\1\10\1\36\1\46"+
    "\1\37\1\1\1\11\12\4\1\50\1\47\1\54\1\52\1\53\1\51"+
    "\1\0\1\27\1\31\1\25\1\30\1\20\1\17\1\3\1\26\1\16"+
    "\1\3\1\34\1\14\1\3\1\12\1\35\2\3\1\32\1\22\1\24"+
    "\1\13\1\3\1\23\3\3\1\44\1\63\1\45\1\40\1\2\1\0"+
    "\1\27\1\31\1\25\1\30\1\20\1\17\1\3\1\26\1\16\1\3"+
    "\1\34\1\14\1\3\1\12\1\35\2\3\1\32\1\22\1\24\1\13"+
    "\1\3\1\23\3\3\1\56\1\60\1\57\7\0\1\65\252\0\2\15"+
    "\115\0\1\21\u1ea8\0\1\65\1\65\u0100\0\1\33\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udee5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\2\1\1\3\2\1\1\7\2\1\10\1\11\1\12"+
    "\1\1\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\0\4\5\1\2"+
    "\1\37\1\40\1\37\1\40\4\2\1\0\6\2\1\41"+
    "\2\2\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\4\5\3\2\1\55\1\0"+
    "\1\2\1\0\1\2\1\0\2\2\1\0\5\2\1\5"+
    "\2\0\3\5\1\56\1\2\1\0\1\2\2\57\1\0"+
    "\1\2\1\0\1\2\1\60\2\61\4\2\2\0\1\2"+
    "\2\62\1\0\1\2\2\63\1\0\2\2\2\64\1\2"+
    "\1\0\1\2\2\65\1\0\2\2\1\66\1\0\1\2"+
    "\1\0\1\2\1\67\2\70\2\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\154\0\u0144"+
    "\0\154\0\154\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288"+
    "\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402\0\154"+
    "\0\154\0\154\0\u0438\0\154\0\154\0\154\0\154\0\154"+
    "\0\154\0\154\0\154\0\u046e\0\u04a4\0\u04da\0\u0510\0\154"+
    "\0\154\0\154\0\154\0\154\0\u0546\0\154\0\u057c\0\u05b2"+
    "\0\u05e8\0\u061e\0\154\0\u0654\0\u068a\0\154\0\154\0\330"+
    "\0\330\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\u07ce\0\u0804"+
    "\0\u083a\0\u0870\0\u08a6\0\u08dc\0\330\0\u0912\0\u0948\0\154"+
    "\0\154\0\154\0\154\0\154\0\154\0\154\0\154\0\154"+
    "\0\154\0\u05b2\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c"+
    "\0\u0ac2\0\330\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06"+
    "\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6"+
    "\0\u09ea\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\330\0\u0ec4\0\u0efa"+
    "\0\u0f30\0\154\0\330\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\330"+
    "\0\154\0\330\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u0e58\0\u1116"+
    "\0\u114c\0\154\0\330\0\u1182\0\u11b8\0\154\0\330\0\u11ee"+
    "\0\u1224\0\u125a\0\154\0\330\0\u1290\0\u12c6\0\u12fc\0\154"+
    "\0\330\0\u1332\0\u1368\0\u139e\0\330\0\u13d4\0\u140a\0\u1440"+
    "\0\u1476\0\330\0\154\0\330\0\154\0\330";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\2\7\1\10\1\11"+
    "\1\12\1\13\2\5\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\2\5\1\25\1\26\1\27"+
    "\1\3\2\5\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\3"+
    "\1\7\1\0\5\55\2\7\53\55\1\56\1\57\2\55"+
    "\67\0\1\4\2\5\6\0\3\5\1\0\3\5\1\0"+
    "\11\5\1\0\2\5\31\0\4\5\5\0\3\5\1\0"+
    "\3\5\1\0\11\5\1\0\2\5\31\0\1\60\2\0"+
    "\1\6\61\0\5\61\1\62\1\63\1\61\1\64\55\61"+
    "\1\0\4\5\5\0\1\5\1\65\1\5\1\0\3\5"+
    "\1\0\11\5\1\0\2\5\42\0\1\66\4\0\1\67"+
    "\47\0\4\5\5\0\1\70\2\5\1\0\1\5\1\71"+
    "\1\5\1\0\11\5\1\0\2\5\31\0\4\5\5\0"+
    "\1\5\1\72\1\5\1\0\3\5\1\0\5\5\1\73"+
    "\3\5\1\0\1\5\1\74\31\0\4\5\5\0\2\5"+
    "\1\75\1\0\3\5\1\0\11\5\1\0\2\5\53\0"+
    "\1\76\43\0\4\5\5\0\3\5\1\0\3\5\1\0"+
    "\1\5\1\77\7\5\1\0\2\5\31\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\4\5\1\100\4\5\1\0"+
    "\2\5\31\0\4\5\5\0\3\5\1\0\3\5\1\0"+
    "\10\5\1\101\1\0\2\5\31\0\4\5\5\0\3\5"+
    "\1\0\3\5\1\0\5\5\1\102\3\5\1\0\1\5"+
    "\1\103\31\0\4\5\5\0\3\5\1\0\2\5\1\104"+
    "\1\0\11\5\1\0\1\5\1\105\31\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\10\5\1\106\1\0\2\5"+
    "\31\0\4\5\5\0\3\5\1\0\2\5\1\107\1\0"+
    "\11\5\1\0\2\5\71\0\1\110\76\0\1\111\1\112"+
    "\64\0\1\113\65\0\1\114\65\0\1\115\13\0\5\55"+
    "\2\0\53\55\2\0\2\55\12\0\1\116\11\0\1\117"+
    "\5\0\1\120\27\0\1\121\7\0\1\122\61\0\5\61"+
    "\1\62\1\63\57\61\6\0\1\63\57\0\5\123\1\124"+
    "\1\125\1\123\1\126\55\123\1\0\4\5\5\0\2\5"+
    "\1\127\1\0\3\5\1\0\11\5\1\0\2\5\31\0"+
    "\4\5\5\0\1\130\2\5\1\0\3\5\1\0\11\5"+
    "\1\0\2\5\31\0\4\5\5\0\2\5\1\131\1\0"+
    "\3\5\1\0\11\5\1\0\2\5\31\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\10\5\1\132\1\0\2\5"+
    "\31\0\4\5\5\0\3\5\1\0\3\5\1\133\1\134"+
    "\10\5\1\0\2\5\45\0\2\135\50\0\4\5\5\0"+
    "\3\5\1\135\1\136\2\5\1\0\11\5\1\0\2\5"+
    "\31\0\4\5\5\0\3\5\1\137\1\140\2\5\1\0"+
    "\11\5\1\0\2\5\31\0\4\5\5\0\1\5\1\141"+
    "\1\5\1\0\3\5\1\0\11\5\1\0\2\5\31\0"+
    "\4\5\5\0\3\5\1\0\3\5\1\142\1\143\10\5"+
    "\1\0\2\5\31\0\4\5\5\0\1\144\2\5\1\0"+
    "\3\5\1\0\11\5\1\0\2\5\31\0\4\5\5\0"+
    "\3\5\1\0\1\5\1\145\1\5\1\0\11\5\1\0"+
    "\2\5\31\0\4\5\5\0\3\5\1\0\2\5\1\146"+
    "\1\0\11\5\1\0\2\5\31\0\4\5\5\0\3\5"+
    "\1\0\3\5\1\0\2\5\1\147\6\5\1\0\2\5"+
    "\30\0\5\123\1\124\1\125\1\123\1\150\55\123\6\151"+
    "\1\125\1\151\1\152\65\151\1\152\55\151\5\126\1\153"+
    "\1\154\1\126\1\155\55\126\1\0\4\5\5\0\2\5"+
    "\1\156\1\0\3\5\1\0\11\5\1\0\2\5\31\0"+
    "\4\5\5\0\3\5\1\0\3\5\1\0\3\5\1\157"+
    "\5\5\1\0\2\5\31\0\4\5\5\0\3\5\1\0"+
    "\3\5\1\160\1\161\10\5\1\0\2\5\50\0\1\162"+
    "\46\0\4\5\5\0\3\5\1\0\2\5\1\163\1\0"+
    "\11\5\1\0\2\5\54\0\1\164\42\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\2\5\1\165\6\5\1\0"+
    "\2\5\44\0\1\166\52\0\4\5\5\0\2\5\1\167"+
    "\1\0\3\5\1\0\11\5\1\0\2\5\31\0\4\5"+
    "\5\0\3\5\1\0\2\5\1\170\1\0\11\5\1\0"+
    "\2\5\50\0\1\171\46\0\4\5\5\0\3\5\1\0"+
    "\2\5\1\172\1\0\11\5\1\0\2\5\31\0\4\5"+
    "\5\0\3\5\1\0\3\5\1\0\2\5\1\173\6\5"+
    "\1\0\2\5\31\0\4\5\5\0\3\5\1\0\3\5"+
    "\1\0\5\5\1\174\3\5\1\0\2\5\31\0\4\5"+
    "\5\0\3\5\1\0\3\5\1\0\5\5\1\175\3\5"+
    "\1\0\2\5\31\0\4\5\5\0\1\5\1\176\1\5"+
    "\1\0\3\5\1\0\11\5\1\0\2\5\30\0\5\123"+
    "\1\124\1\125\1\61\1\150\55\123\7\151\1\63\1\152"+
    "\55\151\6\177\1\154\1\177\1\200\65\177\1\200\55\177"+
    "\5\126\1\153\1\154\1\126\1\155\1\61\54\126\1\0"+
    "\4\5\5\0\3\5\1\0\3\5\1\0\2\5\1\201"+
    "\6\5\1\0\2\5\50\0\1\202\46\0\4\5\5\0"+
    "\3\5\1\0\2\5\1\203\1\0\11\5\1\0\2\5"+
    "\55\0\1\204\41\0\4\5\5\0\3\5\1\0\3\5"+
    "\1\0\3\5\1\205\5\5\1\0\2\5\50\0\1\206"+
    "\46\0\4\5\5\0\3\5\1\0\2\5\1\207\1\0"+
    "\11\5\1\0\2\5\31\0\4\5\5\0\3\5\1\210"+
    "\1\211\2\5\1\0\11\5\1\0\2\5\31\0\4\5"+
    "\5\0\1\5\1\212\1\5\1\0\3\5\1\0\11\5"+
    "\1\0\2\5\31\0\4\5\5\0\3\5\1\0\3\5"+
    "\1\0\11\5\1\213\1\214\1\5\31\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\10\5\1\215\1\0\2\5"+
    "\30\0\7\177\1\154\1\200\1\0\54\177\1\0\4\5"+
    "\5\0\3\5\1\216\1\217\2\5\1\0\11\5\1\0"+
    "\2\5\56\0\1\220\40\0\4\5\5\0\3\5\1\0"+
    "\3\5\1\0\4\5\1\221\4\5\1\0\2\5\42\0"+
    "\1\222\54\0\4\5\5\0\1\223\2\5\1\0\3\5"+
    "\1\0\11\5\1\0\2\5\31\0\4\5\5\0\2\5"+
    "\1\224\1\0\3\5\1\0\11\5\1\0\2\5\31\0"+
    "\4\5\5\0\1\225\2\5\1\0\3\5\1\0\11\5"+
    "\1\0\2\5\65\0\1\226\31\0\4\5\5\0\3\5"+
    "\1\0\3\5\1\0\11\5\1\0\1\5\1\227\43\0"+
    "\1\230\53\0\4\5\5\0\1\5\1\231\1\5\1\0"+
    "\3\5\1\0\11\5\1\0\2\5\31\0\4\5\5\0"+
    "\3\5\1\0\3\5\1\0\2\5\1\232\6\5\1\0"+
    "\2\5\42\0\1\233\54\0\4\5\5\0\1\234\2\5"+
    "\1\0\3\5\1\0\11\5\1\0\2\5\50\0\1\235"+
    "\46\0\4\5\5\0\3\5\1\0\2\5\1\236\1\0"+
    "\11\5\1\0\2\5\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5292];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\1\1\2\11\15\1\3\11"+
    "\1\1\10\11\4\1\5\11\1\1\1\11\1\1\1\0"+
    "\2\1\1\11\2\1\2\11\6\1\1\0\11\1\12\11"+
    "\11\1\1\0\1\1\1\0\1\1\1\0\2\1\1\0"+
    "\6\1\2\0\5\1\1\0\1\1\1\11\1\1\1\0"+
    "\1\1\1\0\2\1\1\11\5\1\2\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\2\1\1\11"+
    "\2\1\1\0\1\1\1\11\1\1\1\0\3\1\1\0"+
    "\1\1\1\0\2\1\1\11\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char[] zzBuffer = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String archivo = "";
    StringBuilder cadena = new StringBuilder();

    public String getArchivo() {
        return archivo;
    }

    public void setArchivo(String nombre) {
        this.archivo = nombre;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
      yychar = 1;
    yyline = 1;
    yycolumn = 1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 228) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char[] newBuffer = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(CUPSim.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { ErrorHandler.AddError("Léxico", getArchivo(), "[LEXER]", "El caracter '" + yytext() + "' no pertenece al alfabeto del lenguaje.", yyline, yycolumn);
            } 
            // fall through
          case 58: break;
          case 2: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: identificador");    return new Symbol(CUPSim.identificador, yycolumn, yyline, yytext());
            } 
            // fall through
          case 59: break;
          case 3: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: numero_entero");    return new Symbol(CUPSim.numero_entero, yycolumn, yyline, yytext());
            } 
            // fall through
          case 60: break;
          case 4: 
            { /* Espacios en blanco, se ignoran */
            } 
            // fall through
          case 61: break;
          case 5: 
            { /* Comentarios, se ignoran */
            } 
            // fall through
          case 62: break;
          case 6: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: por");              return new Symbol(CUPSim.por, yycolumn, yyline, yytext());
            } 
            // fall through
          case 63: break;
          case 7: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: div");              return new Symbol(CUPSim.div, yycolumn, yyline, yytext());
            } 
            // fall through
          case 64: break;
          case 8: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: mas");              return new Symbol(CUPSim.mas, yycolumn, yyline, yytext());
            } 
            // fall through
          case 65: break;
          case 9: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: menos");            return new Symbol(CUPSim.menos, yycolumn, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 10: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: pot");              return new Symbol(CUPSim.pot, yycolumn, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 11: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: par_a");            return new Symbol(CUPSim.par_a, yycolumn, yyline, yytext());
            } 
            // fall through
          case 68: break;
          case 12: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: par_c");            return new Symbol(CUPSim.par_c, yycolumn, yyline, yytext());
            } 
            // fall through
          case 69: break;
          case 13: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: cor_a");            return new Symbol(CUPSim.cor_a, yycolumn, yyline, yytext());
            } 
            // fall through
          case 70: break;
          case 14: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: cor_c");            return new Symbol(CUPSim.cor_c, yycolumn, yyline, yytext());
            } 
            // fall through
          case 71: break;
          case 15: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: coma");             return new Symbol(CUPSim.coma, yycolumn, yyline, yytext());
            } 
            // fall through
          case 72: break;
          case 16: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: puco");             return new Symbol(CUPSim.puco, yycolumn, yyline, yytext());
            } 
            // fall through
          case 73: break;
          case 17: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: dospu");            return new Symbol(CUPSim.dospu, yycolumn, yyline, yytext());
            } 
            // fall through
          case 74: break;
          case 18: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: interrogacion");    return new Symbol(CUPSim.interrogacion, yycolumn, yyline, yytext());
            } 
            // fall through
          case 75: break;
          case 19: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: igual");            return new Symbol(CUPSim.igual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 76: break;
          case 20: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: mayor");            return new Symbol(CUPSim.mayor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 77: break;
          case 21: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: menor");            return new Symbol(CUPSim.menor, yycolumn, yyline, yytext());
            } 
            // fall through
          case 78: break;
          case 22: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: not");              return new Symbol(CUPSim.not, yycolumn, yyline, yytext());
            } 
            // fall through
          case 79: break;
          case 23: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: llave_a");          return new Symbol(CUPSim.llave_a, yycolumn, yyline, yytext());
            } 
            // fall through
          case 80: break;
          case 24: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: llave_c");          return new Symbol(CUPSim.llave_c, yycolumn, yyline, yytext());
            } 
            // fall through
          case 81: break;
          case 25: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: or");               return new Symbol(CUPSim.or, yycolumn, yyline, yytext());
            } 
            // fall through
          case 82: break;
          case 26: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: and");              return new Symbol(CUPSim.and, yycolumn, yyline, yytext());
            } 
            // fall through
          case 83: break;
          case 27: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: comilla");          cadena.setLength(0); yybegin(STRING_CAPTURE);
            } 
            // fall through
          case 84: break;
          case 28: 
            { cadena.append(yytext());
            } 
            // fall through
          case 85: break;
          case 29: 
            { System.out.println("Encontro el simbolo: " + cadena.toString() + " >>>> Token: cadena"); yybegin(YYINITIAL); return new Symbol(CUPSim.cadena, yycolumn, yyline, cadena.toString());
            } 
            // fall through
          case 86: break;
          case 30: 
            { cadena.append('\\');
            } 
            // fall through
          case 87: break;
          case 31: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: in");               return new Symbol(CUPSim.r_in, yycolumn, yyline, yytext());
            } 
            // fall through
          case 88: break;
          case 32: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: if");               return new Symbol(CUPSim.r_if, yycolumn, yyline, yytext());
            } 
            // fall through
          case 89: break;
          case 33: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: do");               return new Symbol(CUPSim.r_do, yycolumn, yyline, yytext());
            } 
            // fall through
          case 90: break;
          case 34: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: mod");              return new Symbol(CUPSim.mod, yycolumn, yyline, yytext());
            } 
            // fall through
          case 91: break;
          case 35: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: igualdad");         return new Symbol(CUPSim.igualdad, yycolumn, yyline, yytext());
            } 
            // fall through
          case 92: break;
          case 36: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: flecha");           return new Symbol(CUPSim.flecha, yycolumn, yyline, yytext());
            } 
            // fall through
          case 93: break;
          case 37: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: mayor_igual");      return new Symbol(CUPSim.mayor_igual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 94: break;
          case 38: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: menor_igual");      return new Symbol(CUPSim.menor_igual, yycolumn, yyline, yytext());
            } 
            // fall through
          case 95: break;
          case 39: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: diferente_que");    return new Symbol(CUPSim.diferente_que, yycolumn, yyline, yytext());
            } 
            // fall through
          case 96: break;
          case 40: 
            { cadena.append('\n');
            } 
            // fall through
          case 97: break;
          case 41: 
            { cadena.append('\t');
            } 
            // fall through
          case 98: break;
          case 42: 
            { cadena.append('\r');
            } 
            // fall through
          case 99: break;
          case 43: 
            { cadena.append('\"');
            } 
            // fall through
          case 100: break;
          case 44: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: numero_decimal");   return new Symbol(CUPSim.numero_decimal, yycolumn, yyline, yytext());
            } 
            // fall through
          case 101: break;
          case 45: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: for");              return new Symbol(CUPSim.r_for, yycolumn, yyline, yytext());
            } 
            // fall through
          case 102: break;
          case 46: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: r_nulo");           return new Symbol(CUPSim.r_nulo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 103: break;
          case 47: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: else");             return new Symbol(CUPSim.r_else, yycolumn, yyline, yytext());
            } 
            // fall through
          case 104: break;
          case 48: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: true");             return new Symbol(CUPSim.r_true, yycolumn, yyline, yytext());
            } 
            // fall through
          case 105: break;
          case 49: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: case");             return new Symbol(CUPSim.r_case, yycolumn, yyline, yytext());
            } 
            // fall through
          case 106: break;
          case 50: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: false");            return new Symbol(CUPSim.r_false, yycolumn, yyline, yytext());
            } 
            // fall through
          case 107: break;
          case 51: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: while");            return new Symbol(CUPSim.r_while, yycolumn, yyline, yytext());
            } 
            // fall through
          case 108: break;
          case 52: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: break");            return new Symbol(CUPSim.r_break, yycolumn, yyline, yytext());
            } 
            // fall through
          case 109: break;
          case 53: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: switch");           return new Symbol(CUPSim.r_switch, yycolumn, yyline, yytext());
            } 
            // fall through
          case 110: break;
          case 54: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: return");           return new Symbol(CUPSim.r_return, yycolumn, yyline, yytext());
            } 
            // fall through
          case 111: break;
          case 55: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: default");          return new Symbol(CUPSim.r_default, yycolumn, yyline, yytext());
            } 
            // fall through
          case 112: break;
          case 56: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: function");         return new Symbol(CUPSim.r_function, yycolumn, yyline, yytext());
            } 
            // fall through
          case 113: break;
          case 57: 
            { System.out.println("Encontro el simbolo: " + yytext() + " >>>> Token: continue");         return new Symbol(CUPSim.r_continue, yycolumn, yyline, yytext());
            } 
            // fall through
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
