package com.constantes;

public enum ETipoNodo {
    ROOT,
    ERROR,
    STMT_FUNC,
    STMT_PRINT,
    EXP_NT,
    EXP_OR,
    EXP_AND,
    EXP_NOT,
    EXP_SUMA,
    EXP_RESTA,
    EXP_MENOR,
    EXP_MAYOR,
    EXP_MODULO,
    EXP_POTENCIA,
    EXP_DIVISION,
    EXP_NEGATIVO,
    EXP_IGUALDAD,
    EXP_DIFERENTE,
    EXP_PRIMITIVE,
    EXP_MAYOR_IGUAL,
    EXP_MENOR_IGUAL,
    EXP_MULTIPLICACION,
}
